### ISSUE TITLE
Whitespaces are added to line end when global paths are used

### ISSUE THREAD

**Issue by m-kessler** [ErykMroczek/mofmt#12]
Fixing #3 resulted in a regression: Now whitespaces are added to the statement in the line before lines with global paths.

Format this with mofmt v0.3.2:
```
block Foo
  import Modelica.Units.SI;
  .Modelica.Blocks.Interfaces.BooleanInput b;
end Foo;
```

A single whitespace character is added to the line with the import statement:
```
⋅⋅⋅⋅import⋅Modelica.Units.SI;⋅
```
(Using ⋅ to make whitespaces visible).

**Comment by ErykMroczek** [comment]
Thanks for a bug reporting BTW.
I have defined some tests at the beginning, but it is hard to come up with every possible construct in advance.
I am slowly preparing for 1.0.0, and part of that would be to improve tests coverage, so your feedback as early adopter is quite useful :).
