### ISSUE TITLE
Line endings are not preserved on Windows

### ISSUE THREAD

**Issue by m-kessler** [ErykMroczek/mofmt#32]
mofmt 0.4.1 stores all changed files with LF line endings, also for files using Windows-style CRLF.

To reproduce, perform the following steps (e.g. with Git Bash on Windows):

```
$ printf "model M\r\nextends X;\r\nend M;" > M.mo
$ file M.mo
M.mo: ASCII text, with CRLF line terminators
$ mofmt M.mo
$ file M.mo
M.mo: ASCII text
```

Moreover, line endings in HTML code are not changed, which results in mixed line endings on Windows.
A simple test is to store this code as `Doc.mo` with CRLF:
```
model Doc
    annotation (
      Documentation(
        info = "<html>
Foo
Bar
</html>"));
end Doc;
```

Then run it through mofmt.
`cat -e` shows us that the updated file uses LF for the lines with regular Modelica code and CRLF in the HTML section:

```
$ cat -e Doc.mo
model Doc$
    annotation ($
      Documentation($
        info = "<html>^M$
Foo^M$
Bar^M$
</html>"));$
$
end Doc;$
```

**Comment by m-kessler** [comment]
In my opinion the line endings should be preserved. Two reasons for Windows users:

1. Git for Windows uses `autocrlf=true` as default (set in `C:\ProgramData\Git\config`), so most Windows users will use this setting
2. I think Dymola on Windows always stores with CRLF. I am not aware of an option to change that.

Hence, a typical Dymola user working on Windows has .mo files with CRLF. Running mofmt on those files will show lots of changed files in `git status`. They disappear when you stage them, but this is annoying and confusing.

**Comment by ErykMroczek** [comment]
I guess you're right. I was just me being lazy.
