### ISSUE TITLE
Internal error for `redeclare replaceable`

### ISSUE THREAD

**Issue by m-kessler** [ErykMroczek/mofmt#34]
mofmt 0.4.1 does not support `redeclare replaceable`.

Here is a minimum example:
```
model M
  extends X(
    redeclare replaceable Sine x);
end M;
```

mofmt crashes with this message:
```
thread 'main' panicked at C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\mofmt-0.4.1\src\formatting.rs:1025:22:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

When the keyword `replaceable` is removed, the code can be formatted.

A more complex real-world example is e.g. `Modelica.Fluid.Valves.ValveVaporizing`.

**Comment by ErykMroczek** [comment]
Yeah, I noticed that, and it was fixed already in [`d51bae6`](https://github.com/ErykMroczek/mofmt/commit/d51bae6011843d1bed41f088b43ab5874494abfd), so version 0.4.2 will work properly.
