### ISSUE TITLE
Missing support for Q-IDENTs with whitespaces and double quotes

### ISSUE THREAD

**Issue by m-kessler** [ErykMroczek/mofmt#4]
Modelica allows to have spaces and double quotes in Q-IDENTS (see https://specification.modelica.org/maint/3.6/lexical-structure.html#identifiers for details).

However, mofmt cannot format code when it contains such Q-IDENTS:
```
model 'foo bar'
end 'foo bar';

block '"foo"'
end '"foo"';
```

Looking at [Q-CHAR in ModelicaLexer.g4](https://github.com/ErykMroczek/mofmt/blob/25730487b4431fb0fb39573c511caca45ac02ded/grammar/ModelicaLexer.g4#L126:L139) it seems like `' '` is missing, same for `'"'`.

Is this an error or a known limitation of mofmt? 

Both cases are very rare, so I think it would be enough to mention in the docs that this is not supported (unless it's easy to fix).

**Comment by ErykMroczek** [comment]
Yup, I noticed that `mofmt` has some issues in a grammar definition, but not this one. Should be quick to fix.
