### ISSUE TITLE
UTF8 files with BOM are not understood

### ISSUE THREAD

**Issue by m-kessler** [ErykMroczek/mofmt#40]
Older Dymola versions had the bad habit to store in modelica code in UTF8 encoding with BOM.

If such a file is formatted, mofmt crashes with:
```
thread 'main' panicked at C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\moparse-0.1.4\src\lexing.rs:349:38:
byte index 1 is not a char boundary; it is inside '\u{feff}' (bytes 0..3) of `﻿within MyLibrary.UsersGuide;
...
```

To reproduce, add a BOM to an UTF8-encoded .mo-file, e.g. with
```
sed -i '1s/^/\xef\xbb\xbf/' myfile.mo
```
then run mofmt on it.

Meanwhile Dymola does not store with BOM any more. Therefore, I think a note in the mofmt doc would be enough that only UTF8 encoded files without BOM are supported.

**Comment by ErykMroczek** [comment]
Addressed in [`9540159`](https://github.com/ErykMroczek/mofmt/commit/954015970b9317e82489577fd73fafcd9821e073)
