### ISSUE TITLE
Empty lines in if statemens and similar are not preserved

### ISSUE THREAD

**Issue by m-kessler** [ErykMroczek/mofmt#48]
It can be desirable to add some empty lines in large or nested if-statements to improve readability.
Unfortunately mofmt removes them, unless a comment follows.
It would be nice to allow a maximum of one empty line before and after each statement inside the if-statement.

The same is true for for-, while- and when-statements.

Use this example code to reproduce:

```
function f

  extends Base;

equation

  if a >= 0 then

    // comment
    y = 1;

  else

    y = 2;

  end if;

  for i in 1 : z loop

    // comment
    x[i] = 1;

  end for;

end f;
```

mofmt formats it to:
```
...
equation

  if a >= 0 then

    // comment
    y = 1;
  else
    y = 2;
  end if;

  for i in 1 : z loop

    // comment
    x[i] = 1;
  end for;

end;
```

But the desired output would be what we used as input.

**Comment by ErykMroczek** [comment]
Implemented in a08926e.

I neglected this for some time, but a new version will be released somewhere next week.
